language: swift
osx_image: xcode11

sudo: required
addons:
  homebrew:
    taps:
    - bow-swift/nef
    packages:
    - nef

env:
  global:
    - PROJECT="./project/nef.xcodeproj"
    - JOB="XCODE"
    - DEST="arch=x86_64"
    - SCHEME="nef"
    - SDK="macosx"
    - ACTION="test"

jobs:
  include:
    # No matrix support in Stages, but this is a matrix hack:
    # Declare the same stage name multiple times to test multiple versions.
    # Using a YAML alias to prevent redundancy.
    # https://github.com/travis-ci/travis-ci/issues/8295#issuecomment-454167006
    - &test
      stage: test
      script:
        - set -o pipefail
        - xcodebuild "$ACTION" -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO -destination "$DEST" | xcpretty -c
    - stage: verify documentation
      before_install:
        - gem update --system
        - gem install cocoapods
      script:
        - nef compile contents/Documentation
    - stage: deploy microsite
      if: branch = master AND type != pull_request
      script:
        - nef jekyll --project contents/Documentation --output docs --main-page contents/Home.md
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: docs
        target-branch: gh-pages
        on:
          all_branches: true
