os: osx
language: objective-c
osx_image: xcode11

addons:
  homebrew:
    taps:
      - bow-swift/nef
    packages:
      - nef

env:
  global:
    - PROJECT="./project/nef.xcodeproj"
    - JOB="XCODE"
    - DEST="arch=x86_64"
    - SCHEME="CoreTests"
    - SDK="macosx"
    - ACTION="test"

jobs:
  include:
    - stage: test
      script:
        - set -o pipefail
        - xcodebuild "$ACTION" -project "$PROJECT" -scheme "$SCHEME" -sdk "$SDK" ONLY_ACTIVE_ARCH=NO -destination "$DEST" | xcpretty -c
    - stage: verify documentation
      before_install:
        - gem update --system
        - gem install cocoapods
      script:
        - nef compile Documentation.app
    - stage: deploy microsite
      if: branch = master AND type != pull_request
      install:
        - gem install bundler --force
        - bundle install --gemfile docs/Gemfile --path vendor/bundle  
      script:
        - nef jekyll --project Documentation.app --output docs --main-page Documentation.app/jekyll/Home.md
        - BUNDLE_GEMFILE=./docs/Gemfile bundle exec jekyll build -s docs -d gen-docs
      deploy:
        provider: pages
        edge: true
        cleanup: false
        token: $GITHUB_TOKEN
        keep_history: true
        local_dir: gen-docs
        target_branch: gh-pages
        on:
          all_branches: true
