name: nef verify documentation

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.0.0.app/Contents/Developer
    - name: Compile documentation
      run: |
        brew install nef
        gem install cocoapods -v 1.9.1
        nef compile --project Documentation.app
