name: Verify Xcode integrity

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch Xcode version
      run: sudo xcode-select -s /Applications/Xcode_11.4.1.app/Contents/Developer
    - name: Compile project
      run: |
        set -o pipefail
        xcodebuild -project ./project/nef.xcodeproj -scheme nef | xcpretty -c
