name: Verify Xcode integrity

on: [pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Switch to Xcode 12
      run: sudo xcode-select -s /Applications/Xcode_12.0.0.app/Contents/Developer
    - name: Compile project
      run: |
        set -o pipefail
        xcodebuild -project ./project/nef.xcodeproj -scheme nef | xcpretty -c
